dependencies:
  cellular:
    url: github.com/toitware/cellular
    version: ^1.1.0
  gnss_location:
    url: github.com/toitware/toit-gnss-location
    version: ^1.0.2
  location:
    url: github.com/toitware/toit-location
    version: ^1.0.0
